{ ... }: ''
  #autogenerated = 1 # remove this line to remove the warning

  # See https://wiki.hyprland.org/Configuring/Keywords/ for more
  $mod = SUPER

  ${
    with builtins; let
      modulesDir = builtins.toPath ./modules;
      skipFiles = [ "autostart.nix" ];
      modulesFiles = filter (file: any (elem: file != elem) (skipFiles)) (attrNames (readDir "${modulesDir}"));
      modulesContent = map (cfg: (readFile "${modulesDir}/${cfg}") + "\n") (modulesFiles);
      combinedContent = foldl' (acc: value: acc + value) "" modulesContent;
    in combinedContent
  }
''
