{ ... }: ''
  #autogenerated = 1 # remove this line to remove the warning

  # See https://wiki.hyprland.org/Configuring/Keywords/ for more
  $mod = SUPER

  ${builtins.readFile ./modules/monitor.conf}
  ${builtins.readFile ./modules/input.conf}
  ${builtins.readFile ./modules/decoration.conf}
  ${builtins.readFile ./modules/animations.conf}
  ${builtins.readFile ./modules/debug.conf}
  ${builtins.readFile ./modules/binds.conf}
  ${builtins.readFile ./modules/env.conf}
  ${builtins.readFile ./modules/gestures.conf}
  ${builtins.readFile ./modules/group.conf}
  ${builtins.readFile ./modules/misc.conf}
  ${builtins.readFile ./modules/general.conf}
  ${builtins.readFile ./modules/workspaces.conf}
  ${builtins.readFile ./modules/layout.conf}
  ${builtins.readFile ./modules/window.conf}
  ${builtins.readFile ./modules/apps.conf}
  ${builtins.readFile ./modules/submap.conf}
  ${builtins.readFile ./modules/window_rules.conf}
  ${builtins.readFile ./modules/window.conf}
''
