{
  activeStyle ? null,
  ...
}:
''
  #autogenerated = 1 # remove this line to remove the warning

  # See https://wiki.hyprland.org/Configuring/Keywords/ for more
  $mod = SUPER

  # load the modules
  ${
    with builtins;
    let
      dir = toPath ./modules;
      skip = [
        "autostart.nix"
        "decoration.conf" # skip the decoration for activeStyle variable
      ];
      dirs = readDir "${dir}";
      files = filter (file: (dirs.${file} == "regular") && (all (elem: file != elem) skip)) (
        attrNames dirs
      );
      modules = map (cfg: (readFile "${dir}/${cfg}") + "\n") (files);
      merged = foldl' (acc: value: acc + value) "" modules;
      decoration =
        if activeStyle != null then readFile activeStyle else readFile "${dir}/decoration.conf";
    in
    merged + "\n" + decoration
  }

  # load the plugins
  plugin {
    ${
      with builtins;
      let
        dir = toPath ./plugins;
        dirs = readDir "${dir}";
        skip = [ ];
        files = filter (file: (dirs.${file} == "regular") && (all (elem: file != elem) skip)) (
          attrNames dirs
        );
        plugins = map (cfg: (readFile "${dir}/${cfg}") + "\n") (files);
        merged = foldl' (acc: value: acc + value) "" plugins;
      in
      merged
    }
  }
''
